-- 코드를 입력하세요
SELECT
A.AUTHOR_ID
, A.AUTHOR_NAME
, B.CATEGORY
, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID
, A.AUTHOR_NAME
, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC