
SELECT B.CATEGORY
, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES A
INNER JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(A.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC