-- 코드를 입력하세요
SELECT
ANIMAL_ID
, NAME
FROM
(
    SELECT
    A.ANIMAL_ID
    , B.NAME
    , ROW_NUMBER() OVER(ORDER BY B.DATETIME - A.DATETIME DESC) AS RANKING
    FROM ANIMAL_INS A
    INNER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
    ) T1
WHERE RANKING IN (1, 2)
ORDER BY RANKING ASC