SELECT
	C.CAR_ID
	, C.CAR_TYPE
	, 30 * (C.DAILY_FEE* NVL(1 - (P.DISCOUNT_RATE/100), 1)) AS FEE
FROM
(
	SELECT
	CAR_ID
	, CAR_TYPE
	, DAILY_FEE
	FROM CAR_RENTAL_COMPANY_CAR
	WHERE CAR_ID NOT IN (
		SELECT
			CAR_ID
		FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
		WHERE START_DATE <= DATE '2022-11-30'
		AND END_DATE >= DATE '2022-11-01'
    )
    AND CAR_TYPE IN ('세단', 'SUV')
) C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE LIKE '30%'
GROUP BY C.CAR_ID
, C.CAR_TYPE
, C.DAILY_FEE
, P.DISCOUNT_RATE
HAVING 30 * (C.DAILY_FEE* NVL(1 - (P.DISCOUNT_RATE/100), 1)) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC