-- 코드를 입력하세요
SELECT
TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR
, TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH
, U.GENDER
, COUNT(DISTINCT(O.USER_ID)) AS USERS -- 회원의 수이므로, 중복제거 필수
FROM USER_INFO U
INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY')
, TO_CHAR(O.SALES_DATE, 'MM')
, U.GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER