-- 코드를 입력하세요
SELECT
NAME
, DATETIME
FROM
(
    SELECT
    A.NAME
    , A.DATETIME
    , ROW_NUMBER() OVER(ORDER BY A.DATETIME) AS RANKING
    FROM ANIMAL_INS A
    LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.DATETIME IS NULL
)
WHERE RANKING <= 3
ORDER BY RANKING
