SELECT
H.HISTORY_ID
, MIN(C.DAILY_FEE * (H.END_DATE - H.START_DATE + 1) * NVL(P.DISCOUNT_RATE, 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN (
    SELECT
        CAR_TYPE
        , DURATION_TYPE
        , 1 - (DISCOUNT_RATE/100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
) P ON C.CAR_TYPE = P.CAR_TYPE
AND (H.END_DATE - H.START_DATE + 1) >= REGEXP_SUBSTR(P.DURATION_TYPE, '\d+')
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC