SELECT
    FLAVOR
FROM (
SELECT
    H.FLAVOR
    , SUM(H.TOTAL_ORDER + J.TOTAL_ORDER) AS CNT
FROM FIRST_HALF H
INNER JOIN JULY J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY CNT DESC
)
WHERE ROWNUM <= 3