-- 코드를 입력하세요
SELECT
A.APNT_NO
, P.PT_NAME
, P.PT_NO
, A.MCDP_CD
, D.DR_NAME
, A.APNT_YMD
FROM PATIENT P
INNER JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID AND D.MCDP_CD = A.MCDP_CD
WHERE A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
ORDER BY A.APNT_YMD