SELECT
T1.HOUR
, COUNT(O.ANIMAL_ID) AS COUNT
FROM (
    SELECT
    LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) T1
LEFT JOIN ANIMAL_OUTS O ON T1.HOUR = TO_CHAR(O.DATETIME, 'HH24')
GROUP BY T1.HOUR
ORDER BY T1.HOUR