SELECT
P.MEMBER_NAME
, R.REVIEW_TEXT
, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE P
INNER JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN
(
    SELECT
    MEMBER_ID
    FROM (
        SELECT
        R.MEMBER_ID
        , RANK() OVER(ORDER BY COUNT(R.REVIEW_ID) DESC) AS RN
        FROM REST_REVIEW R
        GROUP BY R.MEMBER_ID
    ) T1
    WHERE RN = 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT