-- 코드를 입력하세요
SELECT
'/home/grep/src/' || FI.BOARD_ID || '/' || FI.FILE_ID || FI.FILE_NAME || FI.FILE_EXT AS FILE_PATH
FROM
(
    SELECT
    ROW_NUMBER() OVER (ORDER BY VIEWS DESC) AS NUM
    , BOARD_ID
    FROM USED_GOODS_BOARD
) T1
INNER JOIN USED_GOODS_FILE FI ON T1.BOARD_ID = FI.BOARD_ID
WHERE T1.NUM = 1
ORDER BY FI.FILE_ID DESC